service: serverless-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  # profile: admin
   deploymentBucket:
    name: qifan-deployment-bucket
    maxPreviousDeploymentArtifacts: 3


functions:


resources:
 Resources:
   NewResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: my-new-bucket-qifan

